app = "tinyproxy-app"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8888"

[[services]]
  internal_port = 8888
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443